# Generated by Django 2.2 on 2019-05-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('visit_Product', 'Can visit Product'),)},
        ),
    ]
