# Generated by Django 2.2.1 on 2019-05-16 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_language',
            new_name='song_languages',
        ),
    ]
